### ISSUE TITLE
Add property for review process

### ISSUE THREAD

**Issue by Julian-tib** [TIBHannover/ConfIDent_schema#20]
The ORKG Team is in need of describing the type of review process a conference conducts. 

They indent to link ORKG-descriptions of a paper to the conference it was submitted to. They recently partnered with two conferences where researchers in addition to their normal manuscribt could hand in a ORKG-description of their paper. The conferences descriptions in the ORKG currently look like this:

https://www.orkg.org/orkg/organizations/The_21st_International_Semantic_Web_Conference
https://www.orkg.org/orkg/organizations/SEMANTiCS_Conference

An apparently important part of these descriptions is the type of peer review.

We could offer a list of review types. I suggest to stick to these 7 different types for now: https://www.editage.com/insights/7-common-types-of-academic-peer-review

**Comment by StroemPhi** [comment]
Inplemented as another metric type see: https://tibhannover.github.io/ConfIDent_schema/Metric/
