### ISSUE TITLE
Add Subtitle

### ISSUE THREAD

**Issue by Tim-TIB** [TIBHannover/ConfIDent_schema#34]
Some conferences in the humanities have very long subtitles. This ensures that the titles entered are very long and, for example, obscure the date in the series view. Example the following two conferences:

https://www.confident-conference.org/index.php/Event:1546a94f-3702-4ff7-8c20-6ed778f81c66

Examples series: 

https://www.confident-conference.org/index.php/Event_Series:7b30b7c0-14fd-49b6-996e-0b4c0561cfc7

**Comment by StroemPhi** [comment]
The view issue, is something to file in our SMW tracker, as it is related to the implementation of the schema. In the schema defined here we already have https://tibhannover.github.io/ConfIDent_schema/alternative_name/ which would suit this use case imho. But this field is not yet implemented in the SMW plattform (see [CONFIDENT-393](https://wiki.tib.eu/jira/browse/CONFIDENT-393))

**Comment by StroemPhi** [comment]
To be more clear in this example:
Official Name = Unsichere Zeiten. Herausforderungen gesellschaftlicher Transformationen
Alternative Name = 34. Kongress der Deutschen Gesellschaft für Soziologie

**Comment by StroemPhi** [comment]
Also, in the case of events that use names that are more in line with titles of publications, as seemingly in this example, we would probably be better off with not interpreting it as a subtitle/alternative name but rather as the general topic (https://tibhannover.github.io/ConfIDent_schema/has_topic) of the event. To stay in the example the proper, official name of the event, with which to identify it as part of this distinct series, would thus rather be *34. Kongress der Deutschen Gesellschaft für Soziologie* and the general topic of the event would be *Unsichere Zeiten. Herausforderungen gesellschaftlicher Transformationen*. If we look at more recent events of this series, e.g. [this one](https://soziologie.de/kongresse/kongress-2022), we can see that this interpretation/reading is correct. 

Similarly, looking at https://www.confident-conference.org/index.php/Event:73e9b816-0f55-4a36-b4b0-1c51a2a601ba and checking the [official website](https://www.isa-sociology.org/en/conferences/world-congress/toronto-2018/) of this event, we see that also in this particular case it is indeed not part of the official name but the topic.

@Julian-tib the topic field is not implemented as it is defined in the MDS here, but as the free text part of academic field. We should be adding the topic property in the SMW (no ticket for this yet afaik). Also the field for the event/series name is called "Title" in the SMW but "Official Name" in the MDS, which somehow went under my radar and is, as we can see with this ticket, misleading for the users. I think we really need to sort this out and thereby focus on the fact that events are not publications.
